# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4050cd783f7295700a90ddbfac03d017fd3a06e604ac0b4c7b4d5821356e3ac325e98faf805c9c659226bd75d1c9a2c056a317121790ddbe92889af1eda44a8c

test:
  secret_key_base: b264b8665badbf166750f9e5777c17c490c08d3461e415854a53a5a0838eb3b2009d738f8870ac585b8d5d420b832d30b8bd48f5935b28b0856e0672f3d381c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
