test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

<% config = URI.parse ENV.fetch("CLOUDINARY_URL"){ Rails.env.production? ? raise : "" } %>
cloudinary:
  service: Cloudinary
  cloud_name: <%= config.host %>
  api_key: <%= config.user %>
  api_secret: <%= config.password %>
